### ISSUE TITLE
Could you add a license?

### ISSUE THREAD

**Issue by finnkuusisto** [russs123/flappy_bird#1]
Hey, this is a pretty solid recreation of the original. Nice work. Could I trouble you to add a LICENSE file? I'm working on a little project to play simple games like this with an EMG sensor (i.e. https://www.sparkfun.com/products/13723), but this requires some code modification. Your implementation seems the most straight forward to extend, and I'd love to be able to share it with others for them to try afterward.

**Comment by russs123** [comment]
Sure! MIT license added so you should be able to use the code now. And your project sounds really cool, good luck with it! 👍

**Comment by finnkuusisto** [comment]
Thanks!
